"""Rule-based Pine → Python translator (v0.2.0 SMA crossover only).

The generated Python conforms to the v0.2 strategy contract:

    def strategy(data) -> pd.Series:
        # data: DataFrame with DatetimeIndex and ['Open','High','Low','Close'] columns
        # returns: Series of int positions (0 flat, 1 long), same index as data

When the LLM-backed translator lands (v0.2.1), it will produce the same
shape of output -- only this module is swapped.
"""

from survival_alpha.converter.parser import SmaCrossSpec


_HEADER = '''"""Generated by survival-alpha v0.2.0 from Pine strategy: {name}

Original constructs:
  fast = ta.sma(close, {fast})
  slow = ta.sma(close, {slow})
  ta.crossover(fast, slow)  -> enter long
  ta.crossunder(fast, slow) -> close long
"""

import numpy as np
import pandas as pd


'''

_BODY = '''def strategy(data, fast_length={fast}, slow_length={slow}):
    """SMA crossover strategy.

    Parameters
    ----------
    data : pd.DataFrame
        DatetimeIndex with columns: 'Open', 'High', 'Low', 'Close' (optional 'Volume').

    Returns
    -------
    pd.Series
        Same index as `data`. Values: 0 = flat, 1 = long.
    """
    close = data["Close"]
    fast = close.rolling(fast_length).mean()
    slow = close.rolling(slow_length).mean()

    # ta.crossover(fast, slow): fast was at or below slow, now above it.
    long_entry = (fast > slow) & (fast.shift(1) <= slow.shift(1))
    # ta.crossunder(fast, slow): fast was at or above slow, now below it.
    long_exit  = (fast < slow) & (fast.shift(1) >= slow.shift(1))

    position = pd.Series(0, index=data.index, dtype=int)
    state = 0
    for i in range(len(data)):
        if long_entry.iloc[i]:
            state = 1
        elif long_exit.iloc[i]:
            state = 0
        position.iloc[i] = state
    return position
'''


def translate(spec: SmaCrossSpec) -> str:
    """Produce Python source code implementing the parsed Pine spec."""
    return (
        _HEADER.format(name=spec.strategy_name, fast=spec.fast_length, slow=spec.slow_length)
        + _BODY.format(fast=spec.fast_length, slow=spec.slow_length)
    )
